services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=troncos_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=luisrosimongo
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
